sudo: required

language: node_js
node_js:
  - 12

services:
  - docker

install:
  - npm install

jobs:
  include:
    - stage: audit
      script: npm run audit

    - stage: test
      name: MySQL 5
      script: npm run test-mysql
      env:
        - DOCKER_MYSQL_TAG=5
    - name: MySQL 8
      script: npm run test-mysql
      env:
        - DOCKER_MYSQL_TAG=8
    - name: MariaDB 10.4
      script: npm run test-mariadb
      env:
        - DOCKER_MARIADB_TAG=10.4.12
    - name: Postgres 10
      script: npm run test-postgres
      env:
        - DOCKER_POSTGRES_TAG=10
    - name: Postgres 11
      script: npm run test-postgres
      env:
        - DOCKER_POSTGRES_TAG=11
    - name: Postgres 12
      script: npm run test-postgres
      env:
        - DOCKER_POSTGRES_TAG=12
    - name: MSSQL 2017
      script: npm run test-mssql
      env:
        - DOCKER_MSSQL_TAG=2017-CU17-ubuntu
    - name: MSSQL 2019
      script: npm run test-mssql
      env:
        - DOCKER_MSSQL_TAG=2019-latest
    - name: SQLite
      script: npm run test-sqlite

    - stage: build
      script: npm run build

    - stage: deploy
      script: npm run build
      deploy:
        edge: true
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          branch: master

stages:
  - audit
  - test
  - build
  - deploy
