sudo: required

language: node_js
node_js:
  - 10

services:
  - docker

env:
  - DOCKER_MYSQL_TAG=5 DOCKER_MARIADB_TAG=10.4.12 DOCKER_POSTGRES_TAG=10 DOCKER_MSSQL_TAG=2017-CU17-ubuntu
  - DOCKER_MYSQL_TAG=8 DOCKER_MARIADB_TAG=10.4.12 DOCKER_POSTGRES_TAG=11 DOCKER_MSSQL_TAG=2019-latest

install:
  - npm install

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: build
      script: npm run build
    - stage: deploy
      script: npm run build
      deploy:
        edge: true
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          branch: master

stages:
  - test
  - build
  - deploy
